// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll_backend.Models;

#nullable disable

namespace Payroll_backend.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payroll_backend.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("TipoEmpleadoDiscriminador")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasDiscriminator<string>("TipoEmpleadoDiscriminador").HasValue("Empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Payroll_backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaRevocado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Payroll_backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$0Hiw/UkT/oyVtlu/on2djulD67zhgBo3GmZt3F/IAp.8QHYA.S082",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("Payroll_backend.Models.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("Payroll_backend.Models.Empleado");

                    b.Property<decimal>("SalarioSemanal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Asalariado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ApellidoPaterno = "Mendoza",
                            Departamento = "Tecnología",
                            Nombre = "Carlos",
                            NumeroSeguroSocial = "111-22-333",
                            Tipo = 0,
                            SalarioSemanal = 1250.00m
                        });
                });

            modelBuilder.Entity("Payroll_backend.Models.EmpleadoAsalariadoConComision", b =>
                {
                    b.HasBaseType("Payroll_backend.Models.Empleado");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifadeComision")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("VentasBrutas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("AsalariadoConComision");
                });

            modelBuilder.Entity("Payroll_backend.Models.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("Payroll_backend.Models.Empleado");

                    b.Property<decimal>("TarifadeComision")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("VentasBrutas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Empleados", t =>
                        {
                            t.Property("TarifadeComision")
                                .HasColumnName("EmpleadoPorComision_TarifadeComision");

                            t.Property("VentasBrutas")
                                .HasColumnName("EmpleadoPorComision_VentasBrutas");
                        });

                    b.HasDiscriminator().HasValue("PorComision");
                });

            modelBuilder.Entity("Payroll_backend.Models.EmpleadoPorHora", b =>
                {
                    b.HasBaseType("Payroll_backend.Models.Empleado");

                    b.Property<double>("HorasTrabajadas")
                        .HasColumnType("float");

                    b.Property<decimal>("TarifaPorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PorHora");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ApellidoPaterno = "Gómez",
                            Departamento = "Soporte",
                            Nombre = "Ana",
                            NumeroSeguroSocial = "444-55-666",
                            Tipo = 1,
                            HorasTrabajadas = 40.0,
                            TarifaPorHora = 25.50m
                        });
                });

            modelBuilder.Entity("Payroll_backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Payroll_backend.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Payroll_backend.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
